### ISSUE TITLE
6.0.0 release

### ISSUE THREAD

**Issue by sapegin** [styleguidist/react-styleguidist#517]
It’s all about Markdown examples improvements:

- [x] Modifiers for fenced code examples (#257, #511)
- [x] Default modifiers: `static` and `noeditor`
- [x] Ability to add custom modifiers via style guide config (#269)
- [x] Make modifiers case-insensitive
- [x] Update docs

Optional:

- [x] Remove webpack 1 support (#512)

Not sure about the last one because it turned out to be a lot of work. If anyone wants to help with that — we can do it, otherwise I’d postpone it to the 7.0.0.

**All work will be in the [six](https://github.com/styleguidist/react-styleguidist/tree/six) branch.**

**Comment by n1313** [comment]
Why the major bump?

**Comment by sapegin** [comment]
Because we’re changing default behavior for fenced code blocks with js/jsx/javascript language.

**Comment by n1313** [comment]
How much time do you think it'll take this branch to be fully done, and would it be possible to coincide it with initial offering of plugin API?

**Comment by sapegin** [comment]
Depends on (1) how many people will want to help, (2) will we include webpack removal (I guess not ;-) and (3) what we want to include in initial plugins API.

I guess it’s possible to have *some* undocumented plugin API ;-)

**Comment by stepancar** [comment]
@sapegin  , what reason to "Make modifiers case-insensitive"?

**Comment by stepancar** [comment]
"Ability to add custom modifiers via style guide config" 
Just merge modifiers from styleguide.config with passed to example in .md?

**Comment by sapegin** [comment]
I would ask for a reason to make it case-sensitive ;-) It improves the UI — users don’t have to remember the correct casing. But I think it’d be enough to make space-separated modifiers case-insensitive.

> Just merge modifiers from styleguide.config with passed to example in .md?
> what we should implement?

I mean some kind of filters or transformers that could be defined in the config (and later in plugins) that would allow users to implement thing like this file loader. Something like this could work:

```js
function({ contents, lang, modifiers }) {
  if (typeof modifiers.file === 'string') {
    const filepath = modifiers.file;
    delete modifiers.file;
    return {
       contents: fs.readFileSync(filepath),
       modifiers,
       lang,
  }
}
```

**Comment by stepancar** [comment]
@sapegin, I dont like idea with case-insensitive. Because if implement something like loop on example settings object keys and override all keys with lowercase in example plugins(read as preprocessors) developers will should work with case insensitive parameters. 
```
```jsx {"static": true, "supernoreactexamplepreprocessorwithlongname": true }

We use showCode, if we want to use 'showcode' - we should also support caseinsensitive props for styleguide.config https://react-styleguidist.js.org/docs/configuration.html#showcode

**Comment by sapegin** [comment]
You’re thinking only about your own use case with JSON ;-) For most users it would be space-separated list and there’s no point in memorizing if it’s `showcode` or `showCode` — both should work the same.

**Comment by stepancar** [comment]
@sapegin case-insensitive pushed to https://github.com/styleguidist/react-styleguidist/pull/525

**Comment by stepancar** [comment]
@sapegin could you please update docs and, i think, we can release 6.0.0?

**Comment by sapegin** [comment]
Yeah, I’ll do that! Thanks for the work on that release!! 🍕

**Comment by stepancar** [comment]
@sapegin , do you need any help?

**Comment by n1313** [comment]
How about a beta release?

**Comment by sapegin** [comment]
@stepancar I need more time ;-)

@n1313 Yup, will try to do it in the next few days.

**Comment by stepancar** [comment]
@sapegin, when we can publish six version of RSG?

**Comment by sapegin** [comment]
As soon as I can — you can use the branch already.

**Comment by sapegin** [comment]
🍕 [6.0.0](https://github.com/styleguidist/react-styleguidist/releases/tag/v6.0.0-beta.1) beta is out!!  🍕

**Comment by n1313** [comment]
I have a question after reading https://github.com/styleguidist/react-styleguidist/releases/tag/v6.0.0-beta.1: is there a difference between "live editable preview" and "interactive preview"? If these are the same things then I think they should be described using the same terms to avoid confusion.

**Comment by stepancar** [comment]
I migrated our project to six styleguidist.
Works fine.
Also i added linter for .md files using https://github.com/eslint/eslint-plugin-markdown
It's very helpful linter plugin for styleguidist users

**Comment by sapegin** [comment]
@n1313 Nope, but you’re right we should choose one. Which one do you like more? The second looks simpler ;-)

**Comment by n1313** [comment]
@sapegin I agree

**Comment by sapegin** [comment]
Is there anything we should do before the stable release?

**Comment by tizmagik** [comment]
This is great! Congrats 😁

**Comment by stepancar** [comment]
I think No

**Comment by sapegin** [comment]
🍕 [6.0.0](https://github.com/styleguidist/react-styleguidist/releases/tag/v6.0.0) is out!!!! 🥓

**Comment by sapegin** [comment]
@stepancar Thanks for making this release possible!! 🍕🍦🦄
