### ISSUE TITLE
Is it time to drop Node 4 support yet?

### ISSUE THREAD

**Issue by sapegin** [styleguidist/react-styleguidist#744]
* [Current LTS](https://github.com/nodejs/Release#release-schedule) are 6 and 8, Node 4 is in maintenance.
* [Jest 22](http://facebook.github.io/jest/blog/#good-bye-node-4-welcome-jsdom-11) isn’t supporting Node 4.
* [Webpack 4](https://github.com/webpack/webpack/issues/6064) will not support it (in alpha now).

I guess other tools will follow, so maybe it’s time to drop Node 4 in Styleguidist. That will make life easier.

### Todo

- [ ] Update `engines` field in `package.json`
- [ ] Remove `'use strict';` from all files
- [ ] Remove `strict` rule from all `.eslintrc` files
- [ ] Remove Node 4 from `.travis.yml` (including allow_failures and conditions with TRAVIS_NODE_VERSION == 4)

(Am I missing anything?)

### Notes

Remove `use strict` with `jscodeshift`:

```
npx jscodeshift -t https://gist.githubusercontent.com/skratchdot/8a71a36fbc30bcaa8c6e4bba463f595c/raw/457cf93e3f9ec6eff7037d59a38b4652390edefe/remove-no-strict.js --ignore-config .gitignore .
```

(Note: remove comments like `// @ts-check` or `eslint-disable`.)

**Comment by efusien** [comment]
Webpack 4 is now in Beta and will be released soon as a stable version.
React-styleguidist is not working with Webpack 4 beta.

**Comment by sapegin** [comment]
@efusien It's not related to this issue in any way. Feel free to send a PR with a fix, or create a separate issue with a list of think we need to do to support webpack 4.

**Comment by kohgpat** [comment]
I've made a PR. Please take a look. https://github.com/styleguidist/react-styleguidist/pull/839
